name: Check and build

on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  check:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Kotlin linters runner
        uses: vroy/gha-kotlin-linter@v3
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17.11
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build-docker
        run: |
          now=$(date --utc +"%Y.%-m.%-d.%-H.%-M.%-S")
          img_name="ghcr.io/sa4zet-org/light.config.server"
          docker build . -t $img_name:$now -t $img_name:latest
          docker push $img_name:latest
          docker push $img_name:$now
  
